### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by PortGasMC** [Staartvin/PluginLibrary#3]
https://pastebin.com/eKApN9fZ
 
Plugin Library v1.2
spigot 1.12.2 latest build
latest quest updated:
https://www.spigotmc.org/resources/▶-quests-◀-set-up-goals-for-players.23696/updates

**Comment by Staartvin** [comment]
What plugins are you running? Quests (by fatpigsarefat)?

**Comment by PortGasMC** [comment]
yes im using quests by
fatpigsarefat

**Comment by Staartvin** [comment]
Can you show me your whole startup log?

**Comment by PortGasMC** [comment]
https://pastebin.com/qMYsNFtq

**Comment by Staartvin** [comment]
PluginLibrary either looks for Quests (by HappyPikachu) or for Quests (by fatpigsarefat). If one of them is not found, but the other is, then PluginLibrary gives an error. This error is harmless and hence can safely be ignored. PluginLibrary will work fine. It just states that one of the Quests plugins is found and the other is not.

**Comment by PortGasMC** [comment]
i think fatpigsarefat updated the plugin recently 
i think thats the problema 
you can check it if you want
thanks BTW

**Comment by Staartvin** [comment]
I will take a look and close this issue.
